Fixed useragent escaping

diff --git a/check_http_expect b/check_http_expect
--- a/check_http_expect
+++ b/check_http_expect
@@ -1,15 +1,145 @@
 #!/bin/sh
 
-usage() {
-	echo "Usage:  check_http_expect --url=<url> --find=<string> [--huser=<user>] [--hpass=<pass>] [--lurl=<url>] [--ldata==<data> [--ldata=<data>]]"
-	echo
-	echo "  --url         Target URL"
-	echo "  --find        Find string in source of Target URL ('grep -E'-style regex allowed)"
-	echo "  --huser       (Optional) htaccess username"
-	echo "  --hpass       (Optional) htaccess password"
-	echo "  --lurl        (Optional) Url for POST login"
-	echo "  --ldata       (Optional) POST data (can be specified multiple times)"
+# TODO: check against curl
+
+################################################################################
+#
+# V A R I A B L E S
+#
+################################################################################
+
+# Some creds
+INFO_NAME="check_http_expect"
+INFO_AUTHOR="Patrick Plocke <patrick@plocke.de>"
+INFO_GPGKEY="0x28BF179F"
+INFO_DATE="2015-12-12"
+INFO_LICENSE="MIT"
+INFO_VERSION="0.2"
+
+# Get the path
+export PATH="$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
+
+# Nagios error codes
+EXIT_OK=0
+#EXIT_WARN=1
+EXIT_ERR=2
+EXIT_UNKNOWN=3
+
+
+################################################################################
+#
+# F U N C T I O N S
+#
+################################################################################
+
+############################################################
+# Program Functions
+############################################################
+
+# Check program requirements
+# @output string  Parsed, failed requirements
+# @return integer 0|3
+check_requirements() {
+	if ! command -v curl > /dev/null 2>&1; then
+		printf "[Failed] 'curl' must be installed.\n"
+		return $EXIT_UNKNOWN
+	else
+		printf "[OK] 'curl' is installed.\n"
+		return $EXIT_OK
+	fi
 }
+
+# Give some creds
+# @output string  The creds.
+# @return integer 0
+print_version() {
+	printf "Name:    %s\n" "${INFO_NAME}"
+	printf "Version: %s (%s)\n" "${INFO_VERSION}" "${INFO_DATE}"
+	printf "Author:  %s (%s)\n" "${INFO_AUTHOR}" "${INFO_GPGKEY}"
+	printf "License: %s\n" "${INFO_LICENSE}"
+	return 0
+}
+
+
+# Usage
+# @output string  The usage screen.
+# @return integer 0
+print_usage() {
+	printf "Usage:  check_http_expect --url=<url> --find=<string> [--huser=<user>] [--hpass=<pass>] [--lurl=<url>] [--ldata==<data> [--ldata=<data>]]\n"
+	printf "OR      %s --check\n" "${INFO_NAME}"
+	printf "OR      %s --help\n" "${INFO_NAME}"
+	printf "OR      %s --version\n\n" "${INFO_NAME}"
+	return 0
+}
+
+
+# Help
+# @output string  The help screen.
+# @return integer 0
+print_help() {
+
+	# Show usage first
+	print_usage
+
+	# Show description
+	printf "Check a website (behind .htacess and/or behind POST login) for\n"
+	printf "an expected string or regex expression.\n\n"
+
+	# Show detauls
+	printf "  --url                  Target URL\n"
+	printf "  --find                 Find string in source of Target URL ('grep -E'-style regex allowed)\n"
+	printf "  --huser                [optional] htaccess username\n"
+	printf "  --hpass                [optional] htaccess password\n"
+	printf "  --lurl                 [optional] Url for POST login\n"
+	printf "  --ldata                [optional] POST data (can be specified multiple times)\n\n"
+
+	printf "  --check                Check for program requirements.\n"
+	printf "  --help                 Show this help\n"
+	printf "  --version              Show version information.\n"
+	return 0
+}
+
+
+
+################################################################################
+#
+# M A I N   E N T R Y   P O I N T
+#
+################################################################################
+
+############################################################
+# Check for --check, --help or --version arguments
+############################################################
+if [ "${1}" = "--check" ]; then
+	check_requirements
+	if [ "$?" -ne "0" ]; then
+		exit $EXIT_UNKNOWN
+	else
+		exit $EXIT_OK
+	fi
+fi
+if [ "${1}" = "--help" ]; then
+	print_help
+	exit $EXIT_OK
+fi
+if [ "${1}" = "--version" ]; then
+	print_version
+	exit $EXIT_OK
+fi
+
+############################################################
+# Check requirements
+############################################################
+
+if ! command -v curl > /dev/null 2>&1; then
+	printf "[UNKNOWN] 'curl' is required\n"
+	exit $EXIT_UNKNOWN
+fi
+
+
+############################################################
+# Retrieve arguments
+############################################################
 
 while [ $# -gt 0  ]; do
 	case "$1" in
@@ -46,7 +176,7 @@ while [ $# -gt 0  ]; do
 			;;
 		*)
 			echo "Invalid argument: '${1}'"
-			usage
+			print_usage
 			exit 1
 			;;
 	esac
@@ -54,19 +184,26 @@ while [ $# -gt 0  ]; do
 done
 
 
+############################################################
+# Validate arguments
+############################################################
+
 if [ -z "$url" ]; then
 	echo "Error, You must specify an Url."
-	usage
+	print_usage
 	exit 1
 fi
 
 if [ -z "$find" ]; then
 	echo "Error, You must specify what you are looking for."
-	usage
+	print_usage
 	exit 1
 fi
 
 
+############################################################
+# Go Go Go!!!!
+############################################################
 
 # Add htacess parameters
 if [ ! -z "$huser" ] || [ ! -z "$hpass" ]; then
@@ -99,7 +236,9 @@ if [ ! -z "${lurl}" ]; then
 	rm -f cookie.jar
 else
 	# Connect and curl
-	output="$(curl "${curl_args}" -i -s "${url}")"
+	crawl="curl -s -i ${curl_args} ${url}"
+	output="$(eval "${crawl}")"
+	#output="$(curl "${curl_args}" -i -s "${url}")"
 fi
 
 # Split header and content
@@ -119,14 +258,14 @@ match="$(echo "${data}" | grep -E "${find}" | xargs)"
 
 if [ "$number" -gt 0 ]; then
 	if [ "$number" = "1" ]; then
-		echo "[OK] 1 match found for: \"${find}\"."
+		printf "[OK] 1 match found for: \"%s\" | 'Results'=%d\n" "${find}" "${number}"
 	else
-		echo "[OK] ${number} matches found for: \"${find}\"."
+		printf "[OK] %d matches found for: \"%s\" | 'Results'=%d\n" "${number}" "${find}" "${number}"
 	fi
-	EXIT=0
+	EXIT="$EXIT_OK"
 else
-	echo "[ERROR] No matches found for: \"${find}\"."
-	EXIT=2
+	printf "[ERROR] No matches found for: \"%s\" | 'Results'=0\n" "${find}"
+	EXIT="$EXIT_ERR"
 fi
 
 echo "Http version:  ${http_version}"
